### ISSUE TITLE
Unable to load integration in Home Assistant 2024.4.4

### ISSUE THREAD

**Issue by gralin** [jhansche/ha-birdbuddy#82] opened 2024-04-24 12:52 UTC
Integration fails to load after updating Home Assistant to 2024.4.4. Using version 0.0.19.

![image](https://github.com/jhansche/ha-birdbuddy/assets/3457048/fac87958-c6cb-4689-b431-532807462cbd)
![image](https://github.com/jhansche/ha-birdbuddy/assets/3457048/0a433c29-664c-489e-bca6-987018677838)

**Comment by AuroreVgn** [comment] 2024-04-24 12:58
Hi, 
Same thing here. I am using HAOS on Raspberry Pi 4.
A.

**Comment by AuroreVgn** [comment] 2024-04-24 15:23
Hi, 
I've made a rollback to the previous version of HA (core 2024.4.3) and it's still not working.
Same after deleting and reinstalling BB integration.
It's so sad. :-(
A.

**Comment by dcmeglio** [comment] 2024-04-25 01:13
The issue is a dependency of pybirdbuddy got updated causing an incompatibility. I raised this PR which fixes the issue https://github.com/jhansche/pybirdbuddy/pull/23 this fixed it for me.

**Comment by AuroreVgn** [comment] 2024-04-25 06:53
Thank you! I will wait until the pull request merged :-)

**Comment by ChazyChaxxx** [comment] 2024-04-29 13:19
Hello, I have the same problem since the last update.
![Screenshot_2024-04-29-15-18-43-57_c3a231c25ed346e59462e84656a70e50](https://github.com/jhansche/ha-birdbuddy/assets/100526985/206c570a-fcd4-44b1-b091-a3efa8254018)

**Comment by jhansche** [comment] 2024-05-02 04:05
Sorry for the delay. I didn't notice this because I haven't updated to 2024.4.4 yet. The PR above has been merged, but it won't be available here yet until I get a chance to deploy the update to pypi and then bump it here.

In theory you should be able to manually install the downgraded version that was pinned in the PR above. But I haven't tried that. 

I'll try to get this released in the next few days

**Comment by AuroreVgn** [comment] 2024-05-02 13:57
FYI, it's still doen't work in the last version Core 2024.5.0 :-)
I will try to manually install the new version and I will let you know.

**Comment by jhansche** [comment] 2024-05-02 17:14
Good to know 👍

For the recent visitor issue, there was a recent change to fix recent visitor (#79). Can you confirm what version of the integration you have?

**Comment by AuroreVgn** [comment] 2024-05-02 17:20
I have 0.0.19.

**Comment by jhansche** [comment] 2024-05-02 18:59
Ok, that should be the latest. I guess maybe there was another breaking change in 24.5 😮‍💨

Mind opening a new issue for that?

**Comment by antleyhousehold** [comment] 2024-05-03 06:09
The modification to the JSON manifest works (thanks @AuroreVgn! ) with a reboot of the system.

**Comment by AuroreVgn** [comment] 2024-05-03 06:54
> was Unavailable despite is is "Enable" in the settings.

Done!

**Comment by jhansche** [comment] 2024-05-04 11:32
I just updated to 2024.5.1, and I don't see either of these issues. I didn't have to patch my langcodes version.

There might be another integration that has a conflict, and that's why I'm not seeing it.

**Comment by AuroreVgn** [comment] 2024-05-04 19:19
Maybe we can wait a little before closing this issue in order to see if someone will have the same problem.

**Comment by gralin** [comment] 2024-05-13 17:48
Updated to HA 2024.5.3 and intergation V0.0.20. Everything works now.

**Closed** 2024-05-13 17:48 UTC
